<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transaksi - {{ $namaToko }}</title>
    <style>
        :root{--ink:#17202a;--muted:#66727e;--line:#e2e8ed;--paper:#f5f7f9;--white:#fff;--blue:#1769aa;--green:#18845b;--red:#c44343}
        *{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:system-ui,-apple-system,"Segoe UI",sans-serif}.shell{max-width:1240px;margin:auto;padding:28px 22px 48px}.topbar{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:24px}.eyebrow{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);font-weight:700}.topbar h1{margin:5px 0 0;font-size:30px}.back{color:var(--blue);font-weight:700;text-decoration:none}.panel{background:var(--white);border:1px solid var(--line);border-radius:10px;padding:20px;box-shadow:0 5px 20px rgba(27,45,60,.04)}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.tabs a{padding:11px 15px;border:1px solid var(--line);border-radius:6px;text-decoration:none;color:var(--muted);font-weight:700}.tabs a.active{background:var(--blue);border-color:var(--blue);color:#fff}.filter{display:flex;gap:10px;align-items:end;flex-wrap:wrap;margin-bottom:20px;padding-bottom:18px;border-bottom:1px solid var(--line)}.filter label{font-size:12px;color:var(--muted);font-weight:700;display:block;margin-bottom:5px}.filter input{padding:10px;border:1px solid #cbd5de;border-radius:6px;font:inherit}.filter button{padding:10px 16px;border:0;border-radius:6px;background:var(--ink);color:#fff;font-weight:700;cursor:pointer}.clear{color:var(--muted);font-size:13px;text-decoration:none;padding:10px}.summary{display:flex;gap:28px;flex-wrap:wrap;margin-bottom:18px}.summary strong{display:block;font-size:22px}.summary span{color:var(--muted);font-size:13px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:650px}th{text-align:left;color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.04em;border-bottom:2px solid var(--line);padding:10px 12px}td{padding:13px 12px;border-bottom:1px solid var(--line);font-size:14px;vertical-align:top}tr:last-child td{border-bottom:0}.number{font-weight:800}.badge{display:inline-block;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:800}.badge.masuk{background:#eaf8f1;color:var(--green)}.badge.keluar{background:#fff0f0;color:var(--red)}.empty{text-align:center;color:var(--muted);padding:30px!important}.items{color:var(--muted);font-size:13px;line-height:1.6}@media(max-width:700px){.shell{padding:20px 14px 36px}.topbar{align-items:flex-start;flex-direction:column}.topbar h1{font-size:26px}.panel{padding:16px}}
        .layout{display:flex;min-height:100vh}.sidebar{width:234px;flex:0 0 234px;background:#1e3a5f;color:#fff;display:flex;flex-direction:column;position:sticky;top:0;height:100vh;overflow-y:auto}.brand{display:flex;align-items:center;gap:11px;padding:2px 10px 25px}.brand-mark{width:36px;height:36px;display:grid;place-items:center;border-radius:8px;background:rgba(255,255,255,.18);font-size:22px;}.brand strong,.brand small{display:block}.brand strong{font-size:15px}.brand small{margin-top:3px;color:#d4e3ff;font-size:12px}.nav{padding:9px 12px}.nav a,.logout a{display:flex;align-items:center;gap:13px;color:#dce9ff;text-decoration:none;padding:12px 16px;border-radius:9px;font-size:14px;margin:3px 0}.nav a:hover,.nav a.active,.logout a:hover{background:rgba(255,255,255,.2);color:#fff}.nav-icon{width:18px;text-align:center;font-size:19px}.nav-icon svg{width:18px;height:18px;display:block}.nav-arrow{margin-left:auto;font-size:11px;color:#9db3d1;transition:transform .15s ease}.nav-arrow.down{transform:rotate(90deg)}.nav-submenu{margin:2px 0 6px 33px;display:flex;flex-direction:column;gap:2px}.nav-submenu a{padding:8px 10px;font-size:13px;border-radius:7px;color:#c7d7ee;text-decoration:none;display:block}.nav-submenu a:hover{background:rgba(255,255,255,.12);color:#fff}.nav-submenu a.active{background:rgba(255,255,255,.2);color:#fff;font-weight:700}.sidebar-spacer{flex:1}.logout{border-top:1px solid rgba(255,255,255,.18);padding:14px 12px}.logout a{margin:0}.main{flex:1;min-width:0;padding:25px 31px 38px}.main .shell{max-width:none;margin:0;padding:0}.main .back{display:none}
        @media(max-width:700px){.sidebar{width:62px;flex-basis:62px}.brand{padding:18px 17px}.brand div,.nav a span:not(.nav-icon),.logout a span{display:none}.nav a{justify-content:center;padding:12px 8px}.main{padding:20px 15px}.shell{padding:0}.topbar{align-items:flex-start;flex-direction:column}.topbar h1{font-size:26px}.panel{padding:16px}}
    </style>
</head>
<body>
<div class="layout">
<aside class="sidebar">
    <div class="brand" style="{{ $role === 'admin' ? 'height:84px;padding:22px 24px;gap:12px;' : 'padding:2px 10px 25px;gap:11px;' }}"><span class="brand-mark">🛒</span><div><strong>{{ $namaToko }}</strong><small>{{ $role === 'admin' ? 'Admin Utama' : 'Kasir' }}</small></div></div>
    <nav class="nav">
        <a href="{{ $role === 'admin' ? route('admin.dashboard') : route('kasir.index') }}"><span class="nav-icon">{!! $role === 'admin' ? '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/></svg>' : '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9l1-6h16l1 6"/><path d="M3 9v10a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V9"/><path d="M9 21v-6h6v6"/></svg>' !!}</span><span>{{ $role === 'admin' ? 'Dashboard' : 'Kasir ' }}</span></a>
        @if($role === 'admin')<a href="{{ route('admin.produk') }}"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M21 8l-9-5-9 5v8l9 5 9-5V8z"/><path d="M3 8l9 5 9-5"/><path d="M12 13v8"/></svg></span><span>Produk</span></a><a href="{{ route('admin.kategori') }}"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20.59 13.41L11 3.83A2 2 0 0 0 9.5 3H4a1 1 0 0 0-1 1v5.5a2 2 0 0 0 .59 1.41l9.58 9.59a2 2 0 0 0 2.82 0l4.6-4.6a2 2 0 0 0 0-2.99z"/><circle cx="7.5" cy="7.5" r="1.2"/></svg></span><span>Kategori</span></a><a href="{{ route('admin.supplier') }}"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="1" y="3" width="15" height="13" rx="1"/><path d="M16 8h4l3 3v5h-7z"/><circle cx="5.5" cy="18.5" r="2"/><circle cx="18" cy="18.5" r="2"/></svg></span><span>Supplier</span></a>@else<a href="{{ route('kasir.riwayat') }}"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.5 2"/></svg></span><span>Riwayat</span></a>@endif
        <a href="{{ $role === 'admin' ? route('admin.stok') : route('kasir.stok') }}"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="5" rx="1"/><path d="M4 9v9a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9"/><path d="M10 13h4"/></svg></span><span>Stok</span><span class="nav-arrow">▸</span></a>
        @if($role === 'admin')
            <a class="active" href="{{ $role === 'admin' ? route('admin.laporan') : route('kasir.laporan') }}"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M6 2h9l3 3v17H6z"/><path d="M9 8h6M9 12h6M9 16h4"/></svg></span><span>Transaksi</span></a>
        @endif
        @if($role === 'admin')<a href="{{ route('admin.riwayat.transaksi') }}"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M18 20V10"/><path d="M12 20V4"/><path d="M6 20v-6"/></svg></span><span>Laporan</span></a><a href="{{ route('admin.pengaturan') }}"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg></span><span>Pengaturan</span></a>@endif
    </nav>
    <div class="sidebar-spacer"></div><div class="logout"><a href="{{ route('auth.logout', ['role' => $role]) }}"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="M16 17l5-5-5-5"/><path d="M21 12H9"/></svg></span><span>Keluar</span></a></div>
</aside>
<main class="main"><div class="shell">
    <header class="topbar"><div><div class="eyebrow">{{ strtoupper($role) }} · Rekap Data</div><h1>Transaksi</h1></div><a class="back" href="{{ $role === 'admin' ? route('admin.dashboard') : route('kasir.index') }}">← Kembali</a></header>
    <section class="panel">
        <nav class="tabs"><a class="active" href="{{ route($role . '.laporan', ['jenis' => 'penjualan', 'dari' => $dari, 'sampai' => $sampai]) }}">Laporan Penjualan</a></nav>
        <form class="filter" method="GET"><input type="hidden" name="jenis" value="{{ $jenis }}"><div><label for="dari">Dari tanggal</label><input id="dari" type="date" name="dari" value="{{ $dari }}"></div><div><label for="sampai">Sampai tanggal</label><input id="sampai" type="date" name="sampai" value="{{ $sampai }}"></div><button type="submit">Terapkan</button><a class="clear" href="{{ route($role . '.laporan', ['jenis' => $jenis]) }}">Reset</a></form>

        <div class="summary"><div><strong>Rp {{ number_format($penjualan->sum('total'), 0, ',', '.') }}</strong><span>Total penjualan</span></div><div><strong>{{ $penjualan->count() }}</strong><span>Transaksi</span></div><div><strong>{{ number_format($penjualan->sum(fn ($item) => $item->detail->sum('qty')), 0, ',', '.') }}</strong><span>Barang terjual</span></div></div>
        <div class="table-wrap"><table><thead><tr><th>Waktu</th><th>No. Transaksi</th><th>Item</th><th>Metode</th><th>Total</th></tr></thead><tbody>@forelse($penjualan as $item)<tr><td>{{ $item->created_at->format('d/m/Y H:i') }}</td><td><strong>{{ $item->no_transaksi }}</strong></td><td class="items">@foreach($item->detail as $detail){{ $detail->nama_produk }} × {{ $detail->qty }}@if(!$loop->last), @endif @endforeach</td><td>{{ strtoupper($item->metode_pembayaran ?? '-') }}</td><td class="number">Rp {{ number_format($item->total, 0, ',', '.') }}</td></tr>@empty<tr><td class="empty" colspan="5">Belum ada data penjualan.</td></tr>@endforelse</tbody></table></div>
    </section>
</div></div></main>
</body>
</html>